//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Magicsoft Asia Systems Pte Ltd.")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Magicsoft-Asia 2018")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.524ce28")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]


